/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author MSI GF75
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jEdukasi = new javax.swing.JPanel();
        edukasi = new javax.swing.JLabel();
        jskedul = new javax.swing.JPanel();
        skedul = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jAbout = new javax.swing.JPanel();
        about = new javax.swing.JLabel();
        bgn = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximizedBounds(new java.awt.Rectangle(1010, 670, 670, 670));
        setMaximumSize(new java.awt.Dimension(1010, 670));
        setPreferredSize(new java.awt.Dimension(1010, 670));

        jPanel1.setPreferredSize(new java.awt.Dimension(1010, 670));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jEdukasi.setBackground(new java.awt.Color(51, 51, 51));

        edukasi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/icon1.png"))); // NOI18N
        edukasi.setText("jLabel2");
        edukasi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                edukasiMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jEdukasiLayout = new javax.swing.GroupLayout(jEdukasi);
        jEdukasi.setLayout(jEdukasiLayout);
        jEdukasiLayout.setHorizontalGroup(
            jEdukasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jEdukasiLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(edukasi, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jEdukasiLayout.setVerticalGroup(
            jEdukasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jEdukasiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(edukasi)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        jPanel1.add(jEdukasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, 140, 140));

        jskedul.setBackground(new java.awt.Color(51, 51, 51));

        skedul.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/icon3.png"))); // NOI18N
        skedul.setText("jLabel2");
        skedul.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                skedulMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jskedulLayout = new javax.swing.GroupLayout(jskedul);
        jskedul.setLayout(jskedulLayout);
        jskedulLayout.setHorizontalGroup(
            jskedulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jskedulLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(skedul, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jskedulLayout.setVerticalGroup(
            jskedulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jskedulLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(skedul)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        jPanel1.add(jskedul, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 180, 140, 140));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/icon1.png"))); // NOI18N
        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 390, 140, 140));

        jAbout.setBackground(new java.awt.Color(51, 51, 51));

        about.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/icon2.png"))); // NOI18N
        about.setText("jLabel2");
        about.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aboutMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jAboutLayout = new javax.swing.GroupLayout(jAbout);
        jAbout.setLayout(jAboutLayout);
        jAboutLayout.setHorizontalGroup(
            jAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jAboutLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(about, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jAboutLayout.setVerticalGroup(
            jAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jAboutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(about)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        jPanel1.add(jAbout, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 390, 140, 140));

        bgn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/bgn.jpg"))); // NOI18N
        bgn.setText("jLabel1");
        jPanel1.add(bgn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 1050, 710));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1010, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void edukasiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_edukasiMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_edukasiMouseClicked

    private void skedulMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_skedulMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_skedulMouseClicked

    private void aboutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_aboutMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel about;
    private javax.swing.JLabel bgn;
    private javax.swing.JLabel edukasi;
    private javax.swing.JPanel jAbout;
    private javax.swing.JPanel jEdukasi;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jskedul;
    private javax.swing.JLabel skedul;
    // End of variables declaration//GEN-END:variables
}
